title: Changing Nürnberg
description: Webseite von Changing Nürnberg

url: https://changing-nuernberg.github.io/web
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Seitenübersicht
      url: /index.html
    - title: Über uns
      url: /about
    - title: Kontakt
      url: /contact
    - title: Datenschutz
      url: /privacy

social:
    twitter: NAutofrei
    mastodon: https://climatejustice.social/@Nbgautofrei
    instagram: nautofrei
    facebook: nautofrei
