title: Adrian's blog
description: This is my blog where I share my coding journey, my experiences, challenges, and discoveries in the ever-evolving world of programming.
url: "http://localhost:4000"
baseurl: ""
paginate_path: "blog/page:num/"
permalink: "blog/:title/"

# Header Option
# header: large

sass:
  style: compressed

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate
paginate: 5

navigation:
  - title: "Home"
    url: "/index.html"
  - title: "About"
    url: "/about"
  - title: "Contact"
    url: "/contact"

social:
  github: "adrirubio"
  email: "adrian.rubio.punal@gmail.com"

google_analytics: "UA-58263416-1"

disqus:
  shortname: "adri"
