title: CaiTuo's Blog
description: Reflections on software engineering, creativity, and life in the mountains.

url: https://caituoblog.com
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Blog
      url: /
    - title: About
      url: /about
    - title: Contact
      url: /contact

social:
    github: caituo27
    twitter: mcdhdm
    facebook:
    email:
    linkedin:
    youtube:
    tumblr:

google_analytics: "UA-58263416-1"

disqus:
    shortname:
